### ISSUE TITLE
Lessen dependency on Drawer and Device Preview

### ISSUE THREAD

**Issue by stargazing-dino** [the-mac/integration_test_preview#3]
I think a package like this is actually really needed in the Flutter ecosystem but the setup process is really too much. It would be great to see this simplified.

It's also a bit weird that this package considers `device_preview` its surface of interaction (as in it specifically relies on it `device_preview` and the sidebar being there to function) rather than using something lower level such as implicitly resizing screen through `integration_test` and wrapping that image around `device_frame` if necessary.

**Comment by non-profit-lynn** [comment]
Hi @Nolence we would be willing to see pull requests for improvements. But, the goal of the "Getting Started" and "Usage" sections of the README is to allow for more than just Android UI, or just iOS UI integration testing. We use both and test against both (MaterialApp and CupertinoApp), in the end the setup/example provides generated screenshots of the UI previews for both Android & iOS.

Alternatively, you have the dependency of the [Integration Test Helper](https://pub.dev/packages/integration_test_helper) package available separately...

![Screen Shot 2022-04-02 at 5 36 59 PM](https://user-images.githubusercontent.com/35737619/161402023-f0ba16ef-cce7-4bba-8269-52c238bc3c88.png)

If you are not interested in creating a pull request, I would suggest the Integration Test Helper [Package](https://pub.dev/packages/integration_test_helper) or [Repo](https://github.com/the-mac/integration_test_helper). If you do not want to use device preview the way that we have in this dependent package, that package does not use any kind of surface of interaction for integration testing, but has a similar API.

Would you be interested in a pull request for the suggested changes?

**Comment by cdm2012** [comment]
The latest changes to the package supports no toolbar (by default). It now sets the device programmatically.
